/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Route.Stops;

import Inspector_Machine.Action;
import Route.JourneyRecord.RouteJourneys;
import Route.RouteUI;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Shakuni
 */
public class ShowStops extends javax.swing.JFrame {

    /**
     * Creates new form ShowStops
     */
    RouteJourneys routeJourney;
    RouteUI routeUI;
    
    public ShowStops(RouteJourneys frame) {
        initComponents();
        ArrayList <Stops> stopsList= null;
        StopsClass  stopsClass = new StopsClass();
        stopsList = stopsClass.stopsDeserialization();
        int i =0;
        for(Stops mk :stopsList){
            //System.out.println(bk.getMemberNumber());
            stopsTable.setValueAt(mk.getStopID(), i, 0);
            stopsTable.setValueAt(mk.getZoneID(), i, 1);
            stopsTable.setValueAt(mk.getName(), i, 2);
            stopsTable.setValueAt(mk.getLatitude(), i, 3);
            stopsTable.setValueAt(mk.getLongitude(), i, 4);
            i++;
        }
        this.routeJourney=frame;
        StopsPanel.add(journeyPanel);
        StopsPanel.remove(routeUIPanel);
//        StopsPanel.repaint();
//        StopsPanel.revalidate();
    }
    public ShowStops(RouteUI frame2) {
        initComponents();
        ArrayList <Stops> stopsList= null;
        StopsClass  stopsClass = new StopsClass();
        stopsList = stopsClass.stopsDeserialization();
        int i =0;
        for(Stops mk :stopsList){
            //System.out.println(bk.getMemberNumber());
            stopsTable.setValueAt(mk.getStopID(), i, 0);
            stopsTable.setValueAt(mk.getZoneID(), i, 1);
            stopsTable.setValueAt(mk.getName(), i, 2);
            stopsTable.setValueAt(mk.getLatitude(), i, 3);
            stopsTable.setValueAt(mk.getLongitude(), i, 4);
            i++;
        }
        this.routeUI=frame2;
        StopsPanel.remove(journeyPanel);
        StopsPanel.add(routeUIPanel);
//        StopsPanel.repaint();
//        StopsPanel.revalidate();
    }
    
    public ShowStops() {
        initComponents();
        ArrayList <Stops> stopsList= null;
        StopsClass  stopsClass = new StopsClass();
        stopsList = stopsClass.stopsDeserialization();
        int i =0;
        for(Stops mk :stopsList){
            //System.out.println(bk.getMemberNumber());
            stopsTable.setValueAt(mk.getStopID(), i, 0);
            stopsTable.setValueAt(mk.getZoneID(), i, 1);
            stopsTable.setValueAt(mk.getName(), i, 2);
            stopsTable.setValueAt(mk.getLatitude(), i, 3);
            stopsTable.setValueAt(mk.getLongitude(), i, 4);
            i++;
        }
        StopsPanel.remove(journeyPanel);
        StopsPanel.remove(routeUIPanel);
//        StopsPanel.repaint();
//        StopsPanel.revalidate();
    }

    public ShowStops(Action aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StopsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stopsTable = new javax.swing.JTable();
        journeyPanel = new javax.swing.JPanel();
        destinationStop = new javax.swing.JButton();
        selectStop = new javax.swing.JButton();
        sourceStop = new javax.swing.JButton();
        routeUIPanel = new javax.swing.JPanel();
        RouteStopsSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stopsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Stop ID", "Zone ID", "Name", "Latitude", "Longitude"
            }
        ));
        jScrollPane1.setViewportView(stopsTable);

        destinationStop.setText("Set Destination Stop");
        destinationStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationStopActionPerformed(evt);
            }
        });

        selectStop.setText("Select Stops");
        selectStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectStopActionPerformed(evt);
            }
        });

        sourceStop.setText("Set Source Stop");
        sourceStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout journeyPanelLayout = new javax.swing.GroupLayout(journeyPanel);
        journeyPanel.setLayout(journeyPanelLayout);
        journeyPanelLayout.setHorizontalGroup(
            journeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(journeyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sourceStop)
                .addGap(52, 52, 52)
                .addComponent(destinationStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(selectStop, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        journeyPanelLayout.setVerticalGroup(
            journeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(journeyPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(journeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectStop)
                    .addComponent(sourceStop)
                    .addComponent(destinationStop))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        RouteStopsSelect.setText("Select Stop");
        RouteStopsSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RouteStopsSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout routeUIPanelLayout = new javax.swing.GroupLayout(routeUIPanel);
        routeUIPanel.setLayout(routeUIPanelLayout);
        routeUIPanelLayout.setHorizontalGroup(
            routeUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routeUIPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RouteStopsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        routeUIPanelLayout.setVerticalGroup(
            routeUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routeUIPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(RouteStopsSelect)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout StopsPanelLayout = new javax.swing.GroupLayout(StopsPanel);
        StopsPanel.setLayout(StopsPanelLayout);
        StopsPanelLayout.setHorizontalGroup(
            StopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StopsPanelLayout.createSequentialGroup()
                .addGroup(StopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StopsPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(journeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StopsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(routeUIPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        StopsPanelLayout.setVerticalGroup(
            StopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StopsPanelLayout.createSequentialGroup()
                .addGroup(StopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StopsPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StopsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(routeUIPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addComponent(journeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StopsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(StopsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourceStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceStopActionPerformed
        int id1 = stopsTable.getSelectedRow();
        String SID = stopsTable.getValueAt(id1, 0).toString();
        JOptionPane.showMessageDialog(null, SID);
        routeJourney.setSourceID(SID);
        this.setVisible(false);
    }//GEN-LAST:event_sourceStopActionPerformed

    private void destinationStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationStopActionPerformed
        int id2 = stopsTable.getSelectedRow();
        String DID = stopsTable.getValueAt(id2, 0).toString();
        JOptionPane.showMessageDialog(null, DID);
        routeJourney.setDistinationID(DID);
        this.setVisible(false);
    }//GEN-LAST:event_destinationStopActionPerformed

    private void selectStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectStopActionPerformed
        int [] index = stopsTable.getSelectedRows();
        Object [][] rowValue = new Object[index.length][5];
        for(int i = 0; i< index.length; i++){
            for(int y=0;y<5;y++){
                rowValue[i][y] = stopsTable.getValueAt(index[i], y);
            }            
        }
        routeJourney.setStops(rowValue);
        this.setVisible(false);
    }//GEN-LAST:event_selectStopActionPerformed

    private void RouteStopsSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RouteStopsSelectActionPerformed
        int [] index = stopsTable.getSelectedRows();
        Object [][] rowValue = new Object[index.length][5];
        for(int i = 0; i< index.length; i++){
            for(int y=0;y<5;y++){
                rowValue[i][y] = stopsTable.getValueAt(index[i], y);
            }            
        }
//        Object [] rowValue = new Object[5];
//        for(int i = 0; i< index.length; i++){
//            rowValue[0] = stopsTable.getValueAt(index[i], 0);
//            rowValue[1] = stopsTable.getValueAt(index[i], 1);
//            rowValue[2] = stopsTable.getValueAt(index[i], 2);
//            rowValue[3] = stopsTable.getValueAt(index[i], 3);
//            rowValue[4] = stopsTable.getValueAt(index[i], 4);
//        }
        routeUI.setStops(rowValue);
        this.setVisible(false);
    }//GEN-LAST:event_RouteStopsSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowStops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowStops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowStops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowStops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowStops().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RouteStopsSelect;
    private javax.swing.JPanel StopsPanel;
    private javax.swing.JButton destinationStop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel journeyPanel;
    private javax.swing.JPanel routeUIPanel;
    private javax.swing.JButton selectStop;
    private javax.swing.JButton sourceStop;
    private javax.swing.JTable stopsTable;
    // End of variables declaration//GEN-END:variables
}
