/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Route.JourneyRecord;

import Route.RouteUI;
import java.util.ArrayList;

/**
 *
 * @author Shakuni
 */
public class ShowJourneys extends javax.swing.JFrame {

    /**
     * Creates new form ShowJourneys
     */
    RouteUI routeUI = new RouteUI();
    
    public ShowJourneys(RouteUI frame) {
        initComponents();
        ArrayList <JourneyRecord> journeyList= null;
        JourneyRecordClass journeyRecordClass = new JourneyRecordClass();
        journeyList = journeyRecordClass.journeyRecordDeserialization();
        int i =0;
        for(JourneyRecord mk :journeyList){
            //System.out.println(bk.getMemberNumber());
            journeyTable.setValueAt(mk.getSource_Stop(), i, 0);
            journeyTable.setValueAt(mk.getDestination_Stops(), i, 1);
            journeyTable.setValueAt(mk.getDate(), i, 2);
            journeyTable.setValueAt(mk.getTime(), i, 3);
            journeyTable.setValueAt(mk.getTransport_Type(), i, 4);
            journeyTable.setValueAt(mk.getCost(), i, 5);
            //journeyTable.setValueAt(mk.getRow(), i, 6);
            i++;
        }
        this.routeUI=frame;
        JourneyPanel.add(SelectJourneyPanel);
    }
    
    public ShowJourneys() {
        initComponents();
        ArrayList <JourneyRecord> journeyList= null;
        JourneyRecordClass journeyRecordClass = new JourneyRecordClass();
        journeyList = journeyRecordClass.journeyRecordDeserialization();
        int i =0;
        for(JourneyRecord mk :journeyList){
            //System.out.println(bk.getMemberNumber());
            journeyTable.setValueAt(mk.getSource_Stop(), i, 0);
            journeyTable.setValueAt(mk.getDestination_Stops(), i, 1);
            journeyTable.setValueAt(mk.getDate(), i, 2);
            journeyTable.setValueAt(mk.getTime(), i, 3);
            journeyTable.setValueAt(mk.getTransport_Type(), i, 4);
            journeyTable.setValueAt(mk.getCost(), i, 5);
            //journeyTable.setValueAt(mk.getRow(), i, 6);
            i++;
        }
        JourneyPanel.remove(SelectJourneyPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JourneyPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        journeyTable = new javax.swing.JTable();
        SelectJourneyPanel = new javax.swing.JPanel();
        journeySelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        journeyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Source Stop", "Destination Stop", "Date", "Time", "Transport Type", "Cost", "stop"
            }
        ));
        jScrollPane1.setViewportView(journeyTable);

        journeySelect.setText("Select Journey");
        journeySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                journeySelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectJourneyPanelLayout = new javax.swing.GroupLayout(SelectJourneyPanel);
        SelectJourneyPanel.setLayout(SelectJourneyPanelLayout);
        SelectJourneyPanelLayout.setHorizontalGroup(
            SelectJourneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectJourneyPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(journeySelect)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        SelectJourneyPanelLayout.setVerticalGroup(
            SelectJourneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectJourneyPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(journeySelect)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JourneyPanelLayout = new javax.swing.GroupLayout(JourneyPanel);
        JourneyPanel.setLayout(JourneyPanelLayout);
        JourneyPanelLayout.setHorizontalGroup(
            JourneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JourneyPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(JourneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JourneyPanelLayout.createSequentialGroup()
                        .addComponent(SelectJourneyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(126, Short.MAX_VALUE))
                    .addGroup(JourneyPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(126, 126, 126))))
        );
        JourneyPanelLayout.setVerticalGroup(
            JourneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JourneyPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectJourneyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JourneyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JourneyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void journeySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_journeySelectActionPerformed
        int [] index = journeyTable.getSelectedRows();
        Object [] rowValue = new Object[6];
        for(int i = 0; i< index.length; i++){
            rowValue[0] = journeyTable.getValueAt(index[i], 0);
            rowValue[1] = journeyTable.getValueAt(index[i], 1);
            rowValue[2] = journeyTable.getValueAt(index[i], 2);
            rowValue[3] = journeyTable.getValueAt(index[i], 3);
            rowValue[4] = journeyTable.getValueAt(index[i], 4);
            rowValue[5] = journeyTable.getValueAt(index[i], 5);
        }
        routeUI.setJourneys(rowValue);
        this.setVisible(false);
    }//GEN-LAST:event_journeySelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowJourneys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowJourneys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowJourneys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowJourneys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowJourneys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JourneyPanel;
    private javax.swing.JPanel SelectJourneyPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton journeySelect;
    private javax.swing.JTable journeyTable;
    // End of variables declaration//GEN-END:variables
}
