/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TicketMachineSystem;

import Route.JourneyRecord.RouteJourneys;
import Route.JourneyRecord.ShowJourneys;
import Route.RouteUI;
import Route.ShowRoute;
import Route.Stops.RouteStops;
import Route.Stops.ShowStops;
import Route.TransportVehicle.ShowVehicle;
import Route.TransportVehicle.TransportVehicle;
import Route.Zones.RouteZones;
import Route.Zones.ShowZones;

/**
 *
 * @author Shakuni
 */
public class TicketMachineUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form TicketMachineUI
     */
    public TicketMachineUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addJourney = new javax.swing.JButton();
        showJourney = new javax.swing.JButton();
        addRoutes = new javax.swing.JButton();
        showRoutes = new javax.swing.JButton();
        addGate = new javax.swing.JButton();
        showGate = new javax.swing.JButton();
        addZone = new javax.swing.JButton();
        showZone = new javax.swing.JButton();
        addStops = new javax.swing.JButton();
        showStops = new javax.swing.JButton();
        addVehicles = new javax.swing.JButton();
        showVehicles = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        jLabel2.setText("Ticket Machine System");

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        jLabel1.setText("#TravelAnyWhere");

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel3.setText("Zones Management");

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel4.setText("Stops Management");

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel5.setText("Vehicle Management");

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel6.setText("Journey Management");

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel7.setText("Route Management");

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel8.setText("Gate Management");

        addJourney.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        addJourney.setText("Add journey");
        addJourney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJourneyActionPerformed(evt);
            }
        });

        showJourney.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        showJourney.setText("Show Journeys");
        showJourney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showJourneyActionPerformed(evt);
            }
        });

        addRoutes.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        addRoutes.setText("Add Routes");
        addRoutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoutesActionPerformed(evt);
            }
        });

        showRoutes.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        showRoutes.setText("Show Routes");
        showRoutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRoutesActionPerformed(evt);
            }
        });

        addGate.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        addGate.setText("Add Gates");
        addGate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGateActionPerformed(evt);
            }
        });

        showGate.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        showGate.setText("Show Gates");
        showGate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGateActionPerformed(evt);
            }
        });

        addZone.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        addZone.setText("Add Zones");
        addZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addZoneActionPerformed(evt);
            }
        });

        showZone.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        showZone.setText("Show Zones");
        showZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showZoneActionPerformed(evt);
            }
        });

        addStops.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        addStops.setText("Add Stops");
        addStops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStopsActionPerformed(evt);
            }
        });

        showStops.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        showStops.setText("Show Stops");
        showStops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStopsActionPerformed(evt);
            }
        });

        addVehicles.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        addVehicles.setText("Add Vehicles");
        addVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehiclesActionPerformed(evt);
            }
        });

        showVehicles.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        showVehicles.setText("Show Vehicles");
        showVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showVehiclesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(showJourney)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(addJourney, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(showRoutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(addRoutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(showStops, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                                .addComponent(addStops, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(showZone, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(addZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(showVehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addVehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addGate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(showGate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addJourney)
                            .addComponent(addRoutes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showJourney)
                            .addComponent(showRoutes)
                            .addComponent(showVehicles)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(addVehicles)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(addGate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showGate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addZone)
                            .addComponent(addStops))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showZone)
                            .addComponent(showStops))))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehiclesActionPerformed
        TransportVehicle transportVehicle = new TransportVehicle();
        transportVehicle.setVisible(true);
    }//GEN-LAST:event_addVehiclesActionPerformed

    private void addJourneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJourneyActionPerformed
        RouteJourneys RJourneys = new RouteJourneys();
        RJourneys.setVisible(true);
        //getParent().add(RJourneys);
        //getParent().remove(this);
    }//GEN-LAST:event_addJourneyActionPerformed

    private void showJourneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showJourneyActionPerformed
        ShowJourneys SJourney = new ShowJourneys();
        SJourney.setVisible(true);
        //getParent().add(SJourney);
        //getParent().remove(this);
    }//GEN-LAST:event_showJourneyActionPerformed

    private void addRoutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoutesActionPerformed
        RouteUI routeUI = new RouteUI();
        routeUI.setVisible(true);
    }//GEN-LAST:event_addRoutesActionPerformed

    private void showRoutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRoutesActionPerformed
        ShowRoute showRoute = new ShowRoute();
        showRoute.setVisible(true);
    }//GEN-LAST:event_showRoutesActionPerformed

    private void showVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showVehiclesActionPerformed
        ShowVehicle showVehicle = new ShowVehicle();
        showVehicle.setVisible(true);
    }//GEN-LAST:event_showVehiclesActionPerformed

    private void addZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addZoneActionPerformed
        RouteZones zone = new RouteZones();
        zone.setVisible(true);
    }//GEN-LAST:event_addZoneActionPerformed

    private void showZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showZoneActionPerformed
        ShowZones showZones = new ShowZones();
        showZones.setVisible(true);
    }//GEN-LAST:event_showZoneActionPerformed

    private void addStopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStopsActionPerformed
        RouteStops routeStops = new RouteStops();
        routeStops.setVisible(true);
    }//GEN-LAST:event_addStopsActionPerformed

    private void showStopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStopsActionPerformed
        ShowStops showStops = new ShowStops();
        showStops.setVisible(true);
    }//GEN-LAST:event_showStopsActionPerformed

    private void addGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addGateActionPerformed

    private void showGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showGateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGate;
    private javax.swing.JButton addJourney;
    private javax.swing.JButton addRoutes;
    private javax.swing.JButton addStops;
    private javax.swing.JButton addVehicles;
    private javax.swing.JButton addZone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton showGate;
    private javax.swing.JButton showJourney;
    private javax.swing.JButton showRoutes;
    private javax.swing.JButton showStops;
    private javax.swing.JButton showVehicles;
    private javax.swing.JButton showZone;
    // End of variables declaration//GEN-END:variables
}
